/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HeaderBar: typeof import('./components/home/HeaderBar.vue')['default']
    PostCard: typeof import('./components/home/PostCard.vue')['default']
    PostList: typeof import('./components/home/PostList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/home/SideBar.vue')['default']
  }
}
