/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/Auth': RouteRecordInfo<'/Auth', '/Auth', Record<never, never>, Record<never, never>>,
    '/collection': RouteRecordInfo<'/collection', '/collection', Record<never, never>, Record<never, never>>,
    '/list': RouteRecordInfo<'/list', '/list', Record<never, never>, Record<never, never>>,
    '/publish/article': RouteRecordInfo<'/publish/article', '/publish/article', Record<never, never>, Record<never, never>>,
    '/publish/picture': RouteRecordInfo<'/publish/picture', '/publish/picture', Record<never, never>, Record<never, never>>,
    '/work': RouteRecordInfo<'/work', '/work', Record<never, never>, Record<never, never>>,
  }
}
